name: sovereigndb
services:
    postgres:
        image: postgres:${POSTGRES_VERSION:-16}
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-symfony}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
            POSTGRES_DB: ${POSTGRES_DB:-sovereigndb}
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-sovereigndb}", "-U", "${POSTGRES_USER:-symfony}"]
            timeout: 5s
            retries: 5
            start_period: 60s

    pgweb:
        restart: always
        image: sosedoff/pgweb
        ports:
            - "8081:8081"
        links:
            - postgres:postgres
        environment:
            - PGWEB_DATABASE_URL=postgres://${POSTGRES_USER:-symfony}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-sovereigndb}?sslmode=disable
        depends_on:
            - postgres

    symfony:
        build: ./symfony/
        volumes:
            - ../../:/var/www/html
        ports:
            - 8080:8000
        environment:
            POSTGRES_USER: symfony
            POSTGRES_PASSWORD: password
            POSTGRES_DB: sovereigndb
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
        entrypoint: ['symfony', 'server:start']

#    mailer:
#        image: axllent/mailpit
#        ports:
#            - 127.0.0.1:1025:1025
#            - 127.0.0.1:8025:8025
#        environment:
#            MP_SMTP_AUTH_ACCEPT_ANY: 1
#            MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
    postgres-data:
