twig:
    form_themes: ['bootstrap_5_layout.html.twig']
    file_name_pattern: '*.twig'
    globals:
        factions: '@App\Service\FactionService'
        packs: '@App\Service\PackService'

when@test:
    twig:
        strict_variables: true
