alsciende_security:
    resource: "@AlsciendeSecurityBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
   path: /logout

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
