alsciende_security:
    resource: "@AlsciendeSecurityBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
   path: /logout

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
