security:

    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        your_db_provider:
            entity:
                class: AppBundle:User
                property: username
            
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            context: my_security_context
            pattern: ^/api
            anonymous: ~
            guard:
                provider:
                    your_db_provider
                authenticators:
                    - app.token_authenticator

        main:
            context: my_security_context
            anonymous: ~
            guard:
                provider:
                    your_db_provider
                authenticators:
                    - app.form_login_authenticator
        