security:

    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        my_user_provider:
            entity:
                class: AppBundle:User
                property: username
            
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        auth:
            pattern: ^/auth
            security: false
            stateless: false

        main:
            security: true
            stateless: true
            anonymous: ~
            logout: ~
            guard:
                provider:
                    my_user_provider
                authenticators:
                    - app.security.oauth_authenticator

