security:

    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        your_db_provider:
            entity:
                class: AppBundle:User
                property: username
            
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        private_api:
            context: my_security_context
            pattern: ^/api/private/
            anonymous: false
            guard:
                provider:
                    your_db_provider
                authenticators:
                    - app.form_login_authenticator
                    - app.token_authenticator
                entry_point: app.token_authenticator

        public_api:
            context: my_security_context
            pattern: ^/api/public/
            anonymous: ~
            guard:
                provider:
                    your_db_provider
                authenticators:
                    - app.token_authenticator
                    - app.form_login_authenticator
                entry_point: app.token_authenticator

        private_html:
            context: my_security_context
            pattern: ^/(profile|login_check)
            anonymous: false
            guard:
                provider:
                    your_db_provider
                authenticators:
                    - app.form_login_authenticator

        public_html:
            context: my_security_context
            anonymous: ~
            guard:
                provider:
                    your_db_provider
                authenticators:
                    - app.form_login_authenticator
