security:

    providers:
        your_db_provider:
            entity:
                class: AppBundle:User
                property: apiKey

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        private_api:
            pattern: ^/api/private/
            anonymous: false
            guard:
                provider:
                    your_db_provider
                authenticators:
                    - app.token_authenticator
                    - app.form_login_authenticator
                entry_point: app.token_authenticator

        public_api:
            pattern: ^/api/public/
            anonymous: ~
            guard:
                provider:
                    your_db_provider
                authenticators:
                    - app.token_authenticator
                    - app.form_login_authenticator
                entry_point: app.token_authenticator

        private_html:
            pattern: ^/profile
            anonymous: false
            guard:
                provider:
                    your_db_provider
                authenticators:
                    - app.form_login_authenticator
                entry_point: app.form_login_authenticator

        public_html:
            anonymous: ~
