services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $jsonDataPath: '%path_to_json_data%'
            $securityLogger: '@monolog.logger.security'

    # configuration by interface

    _instanceof:
        AppBundle\Behavior\Controller\ApiControllerInterface:
            calls:
                - [setApiService, ['@AppBundle\Service\ApiService']]
        Psr\Log\LoggerAwareInterface:
            calls:
                - [setLogger, ['@logger']]

    # configuration by directory

    AppBundle\:
        resource: '../../src/AppBundle/{Security,Service,Util,Validator,Form,Controller,Command,Mock}'

    AppBundle\Service\DeckCheck\:
        resource: '../../src/AppBundle/Service/DeckCheck'
        tags: [ 'app.deck_check' ]

    AppBundle\Service\DeckSearch\:
        resource: '../../src/AppBundle/Service/DeckSearch'
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
          - 'app.deck_search'

    AppBundle\EventSubscriber\:
        resource: '../../src/AppBundle/EventSubscriber/*'
        tags:
          - 'kernel.event_subscriber'

    AppBundle\Doctrine\EventSubscriber\:
        resource: '../../src/AppBundle/Doctrine/EventSubscriber/*'
        tags:
          - 'doctrine.event_subscriber'

    AppBundle\Validator\Constraints\:
        resource: '../../src/AppBundle/Validator/Constraints/*Validator'
        tags:
          - 'validator.constraint_validator'

    AppBundle\Security\Voter\:
        resource: '../../src/AppBundle/Security/Voter/*'
        tags:
          - 'security.voter'

    AppBundle\Form\Type\:
        resource: '../../src/AppBundle/Form/Type/*'
        tags:
          - 'form.type'

    AppBundle\Serializer\:
        resource: '../../src/AppBundle/Serializer/*'
        public: true
        tags:
          - 'jms_serializer.subscribing_handler'

    # interface aliases

    AppBundle\Behavior\Service\OauthServiceInterface: '@AppBundle\Service\Metagame'

    # configuration by class

    AppBundle\Service\PaypalService:
        arguments:
          - '%paypal_classic_api_username%'
          - '%paypal_classic_api_password%'
          - '%paypal_classic_api_signature%'

    AppBundle\Service\ApiService:
        arguments:
          - '@request_stack'
          - '@jms_serializer'
          - '%http_cache_max_age%'

    AppBundle\Service\FeatureManager:
        arguments:
          - '@doctrine.orm.entity_manager'
          - '%features_period%'

    AppBundle\Service\Metagame:
        arguments:
          - '%metagame_base_uri%'
          - '%kernel.logs_dir%'
          - '%kernel.environment%'
          - '%kernel.debug%'

    AppBundle\Security\CredentialsCacheService:
        public: true
        arguments:
          - '@app.cache'
          - '%access_token_ttl%'

    app.cache:
        public: false
        class: Symfony\Component\Cache\Simple\RedisCache
        arguments: ['@app.redis']

    app.redis:
        public: false
        class: Predis\Client
        arguments: ['%redis_url%']

    # tagged service injection

    AppBundle\Service\DeckValidator:
        arguments: [!tagged app.deck_check]

    AppBundle\Service\DeckSearchService:
        arguments: [!tagged app.deck_search]
