services:
    app.token_authenticator:
        class: AppBundle\Security\TokenAuthenticator
        arguments: ["@doctrine.orm.entity_manager"]
    app.form_login_authenticator:
        class: AppBundle\Security\FormLoginAuthenticator
        arguments: ["@security.password_encoder","@router","@logger"]
