services:
    _instanceof:
        AppBundle\Service\DeckCheck\DeckCheckInterface:
            tags: [ 'app.deck_check' ]

    AppBundle\Service\DeckCheck\:
        resource: '../../src/AppBundle/Service/DeckCheck'

    alsciende_security.oauth_authenticator:
        class: Alsciende\SecurityBundle\Security\OauthAuthenticator
        arguments:
          - "@fos_oauth_server.access_token_manager"

    alsciende_security.form_login_authenticator:
        class: Alsciende\SecurityBundle\Security\FormLoginAuthenticator
        arguments:
          - "@security.password_encoder"
          - "@router"

    alsciende_security.client_manager:
        class: Alsciende\SecurityBundle\Service\ClientManager
        arguments:
          - "@fos_oauth_server.entity_manager"
          - "%fos_oauth_server.model.client.class%"

    alsciende_security.user_manager:
        class: Alsciende\SecurityBundle\Service\UserManager
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@security.password_encoder"
          - "%secret%"

    paypal:
        class: AppBundle\Service\PaypalService
        arguments:
          - "%paypal_classic_api_username%"
          - "%paypal_classic_api_password%"
          - "%paypal_classic_api_signature%"

    app.api:
        class: AppBundle\Service\ApiService
        arguments:
          - "@request_stack"
          - "@jms_serializer"
          - "%http_cache_max_age%"
          - "%kernel.environment%"

    app.deck_validator:
        class: AppBundle\Service\DeckValidator

    app.deck_manager:
        class: AppBundle\Manager\DeckManager
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@serializer"
          - '@app.deck_validator'

    app.comment_manager:
        class: AppBundle\Manager\CommentManager
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@serializer"

    app.review_manager:
        class: AppBundle\Manager\ReviewManager
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@serializer"

    app.ruling_manager:
        class: AppBundle\Manager\RulingManager
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@serializer"

    app.deck_serializer:
        class: AppBundle\Service\DeckSerializer
        arguments:
          - "@app.data_transformer.card_slots"
        tags:
          - name: "jms_serializer.handler"
            type: "AppBundle\\Entity\\Deck"
            format: "json"

    app.canonical_fields_updater:
        class: AppBundle\Util\CanonicalFieldsUpdater

    app.doctrine_card_listener:
        class: AppBundle\Doctrine\CardListener
        arguments:
          - "@app.canonical_fields_updater"
        tags:
          - name: "doctrine.event_subscriber"

    app.data_transformer.card_slots:
        class: AppBundle\Form\DataTransformer\CardSlotsTransformer
        arguments:
          - "@doctrine.orm.entity_manager"

    app.form_type.deck:
        class: AppBundle\Form\Type\DeckType
        arguments:
          - "@app.data_transformer.card_slots"
        tags:
          - "form.type"
