services:
#    app.json_encoder:
#        class: AppBundle\Service\JsonEncoder
#        arguments: ["%kernel.root_dir%", "%json_data%"]
#    app.association_normalizer:
#        class: AppBundle\Service\AssociationNormalizer
#        arguments: ["@doctrine.orm.entity_manager"]
