services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # configuration by directory

    AppBundle\DataFixtures\:
        resource: '../../src/AppBundle/DataFixtures'
        tags:
          - 'doctrine.fixture.orm'
