services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # configuration by directory

    AppBundle\:
        resource: '../../src/AppBundle/{Security,Service,Util,Validator,Form,Controller}'

    AppBundle\Service\DeckCheck\:
        public: false
        resource: '../../src/AppBundle/Service/DeckCheck'
        tags: [ 'app.deck_check' ]

    AppBundle\Service\DeckSearch\:
        public: false
        resource: '../../src/AppBundle/Service/DeckSearch'
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags: [ 'app.deck_search' ]

    AppBundle\EventSubscriber\:
        public: false
        resource: '../../src/AppBundle/EventSubscriber/*'
        tags:
          - "kernel.event_subscriber"

    AppBundle\Doctrine\EventSubscriber\:
        public: false
        resource: '../../src/AppBundle/Doctrine/EventSubscriber/*'
        tags:
          - name: "doctrine.event_subscriber"

    AppBundle\Validator\Constraints\:
        public: false
        resource: '../../src/AppBundle/Validator/Constraints/*Validator'
        tags:
          - "validator.constraint_validator"

    AppBundle\Security\Voter\:
        public: false
        resource: '../../src/AppBundle/Security/Voter/*'
        tags:
          - "security.voter"

    AppBundle\Form\Type\:
        public: false
        resource: '../../src/AppBundle/Form/Type/*'
        tags:
          - "form.type"

    AppBundle\Serializer\:
        public: true
        resource: '../../src/AppBundle/Serializer/*'
        public: true
        tags:
            - { name: jms_serializer.subscribing_handler }

    # configuration by class

    AppBundle\Service\PaypalService:
        arguments:
          - "%paypal_classic_api_username%"
          - "%paypal_classic_api_password%"
          - "%paypal_classic_api_signature%"

    AppBundle\Service\ApiService:
        arguments:
          - "@request_stack"
          - "@jms_serializer"
          - "%http_cache_max_age%"

    AppBundle\Service\TokenManager:
        arguments:
          - "@doctrine.orm.entity_manager"
          - "%access_token_ttl%"

    AppBundle\Service\FeatureManager:
        arguments:
          - "@doctrine.orm.entity_manager"
          - "%features_period%"

    AppBundle\Service\Metagame:
        arguments:
          - "%metagame_base_uri%"
          - "%kernel.logs_dir%"
          - "%kernel.environment%"
          - "%kernel.debug%"
