services:
    alsciende.doctrine_serializer.source_manager:
        class: Alsciende\DoctrineSerializerBundle\Manager\SourceManager
        arguments: ["@alsciende.doctrine_serializer.reference_manager.entity","%alsciende.doctrine_serializer.group%","%alsciende.doctrine_serializer.path%"]
        
    alsciende.doctrine_serializer.reference_manager.entity:
        class: Alsciende\DoctrineSerializerBundle\Manager\Entity\ObjectManager
        arguments: ["@doctrine.orm.entity_manager"]

    alsciende.doctrine_serializer.serializer:
        class: Alsciende\DoctrineSerializerBundle\Serializer
        arguments: ["@alsciende.doctrine_serializer.reference_manager.entity","@alsciende.doctrine_serializer.source_manager","@validator","@annotation_reader","@alsciende.doctrine_serializer.normalizer"]

    alsciende.doctrine_serializer.normalizer:
        class: Alsciende\DoctrineSerializerBundle\Normalizer
        arguments: ["@alsciende.doctrine_serializer.reference_manager.entity","@serializer"]
