services:
    App\SearchQueryBuilder\SearchQueryBuilder:
        autowire: true
        arguments:
            $logger: '@monolog.logger'

    App\Service\SyntaxDecoder:
        autowire: true
        arguments:
            $logger: '@monolog.logger'
