AppBundle\Entity\Pack:
    exclusion_policy: ALL
    accessor_order: alphabetical
    properties:
        id:
            expose: true
            groups: ['Default','Id']
        name:
            expose: true
        position:
            expose: true
        releasedAt:
            expose: true
        size:
            expose: true
        cycle:
            expose: true
            groups: ['Cycle']
        cards:
            expose: true
            groups: ['Cards']
