AppBundle\Entity\Deck:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        createdAt:
            expose: true
        updatedAt:
            expose: true
        name:
            expose: true
        description:
            expose: true
            groups: ['Description']
        format:
            expose: true
        nb_likes:
            expose: true
        published:
            expose: true
        problem:
            expose: true
        primaryClan:
            expose: true
        secondaryClan:
            expose: true
        strain:
            expose: true
            groups: ['Strain']
        user:
            expose: true
            groups: ['User']
        deckCards:
            expose: true
            type: AppBundle\Model\CardSlotCollectionDecorator
            access_type: public_method
            serialized_name: cards
            groups: ['Cards']
        comments:
            expose: true
            groups: ['Comments']
    virtual_properties:
        getVersion:
            serialized_name: version
            type: string
