AppBundle\Entity\Activity:
    exclusion_policy: ALL
    accessor_order: alphabetical
    properties:
        id:
            expose: true
        type:
            expose: true
        personal:
            expose: true
        createdAt:
            expose: true
        deck:
            expose: true
        user:
            expose: true
