AppBundle\Entity\User:
    exclusion_policy: ALL
    accessor_order: alphabetical
    properties:
        id:
            expose: true
        username:
            expose: true
        roles:
            expose: true
            groups: ['Self']
