AppBundle\Entity\Review:
    exclusion_policy: ALL
    accessor_order: alphabetical
    properties:
        id:
            expose: true
        text:
            expose: true
        card:
            expose: true
            groups: ['Card']
        user:
            expose: true
            groups: ['User']
