AppBundle\Entity\Strain:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: ['Default','Head']
        createdAt:
            expose: true
            groups: ['Default','Head']
        head:
            expose: true
            groups: ['Head']
