AppBundle\Entity\Activity:
    exclusion_policy: ALL
    accessor_order: alphabetical
    properties:
        type:
            expose: true
        deck:
            expose: true
            groups: ['Deck']
        createdAt:
            expose: true
