AppBundle\Entity\Token:
    exclusion_policy: ALL
    accessor_order: alphabetical
    properties:
        accessToken:
            expose: true
        tokenType:
            expose: true
        refreshToken:
            expose: true
        expiresAt:
            expose: true
