AppBundle\Entity\Strain:
    exclusion_policy: ALL
    accessor_order: alphabetical
    properties:
        id:
            expose: true
        createdAt:
            expose: true
        head:
            expose: true
            groups: ['Head']
