services:
    alsciende_serializer.source_manager:
        class: Alsciende\SerializerBundle\Manager\SourceManager
        arguments: ["@alsciende_serializer.object_manager.entity","%alsciende_serializer.path%"]
        
    alsciende_serializer.object_manager.entity:
        class: Alsciende\SerializerBundle\Manager\Entity\ObjectManager
        arguments: ["@doctrine.orm.entity_manager"]

    alsciende_serializer.storing_service:
        class: Alsciende\SerializerBundle\Service\StoringService
        arguments: []

    alsciende_serializer.encoding_service:
        class: Alsciende\SerializerBundle\Service\EncodingService
        arguments: []

    alsciende_serializer.normalizing_service:
        class: Alsciende\SerializerBundle\Service\NormalizingService
        arguments: ["@alsciende_serializer.object_manager.entity"]

    alsciende_serializer.serializer:
        class: Alsciende\SerializerBundle\Serializer\Serializer
        arguments: 
            - "@alsciende_serializer.storing_service"
            - "@alsciende_serializer.encoding_service"
            - "@alsciende_serializer.normalizing_service"
            - "@alsciende_serializer.object_manager.entity"
            - "@alsciende_serializer.source_manager"
            - "@validator"
            - "@annotation_reader"
