services:

    alsciende_security.oauth_authenticator:
        class: Alsciende\SecurityBundle\Security\OauthAuthenticator
        arguments:
          - "@alsciende_security.user_manager"

    alsciende_security.user_manager:
        class: Alsciende\SecurityBundle\Service\UserManager
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@security.password_encoder"
          - "%secret%"
